# This workflow will build a Java project and run unit tests with Gradle
# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI With Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test The Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          architecture: x64
      - name: Grant Gradle wrapper (gradlew) sufficient permissions
        run: chmod +x gradlew
      - name: Build the project
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
